name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.2.0  # Substitua pela última versão disponível
  firebase_auth: ^5.1.2   # Substitua pela última versão disponível
  cloud_firestore: ^5.1.0  # Substitua pela última versão disponível
  firebase_storage: ^12.1.1
  image_picker: ^0.8.4+4
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.5
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_api_headers: ^1.1.1
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/tom.png
    - lib/images/lua.png
    - lib/images/thor.png
    - lib/images/mel.png
