name: adogcao
description: "Aplicativo de adoção de animais - Encontre seu companheiro perfeito"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  
  # UI e Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Imagens e Mídia
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  
  # Localização e Mapas
  google_maps_flutter: ^2.9.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  google_api_headers: ^1.1.1
  
  # Estado e Gerenciamento
  provider: ^6.1.2
  get_it: ^7.6.7
  
  # Utilitários
  intl: ^0.19.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  
  # Animações
  lottie: ^3.1.2
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.10
  json_annotation: ^4.8.1

flutter:
  uses-material-design: true

  assets:
    - lib/images/
    - lib/assets/animations/
    - lib/assets/icons/
